marks=[85, 92, 78, 90, 88]
print(type(marks))
print(marks[1:3])
marks.append(95)
print(marks)
marks.sort()
print(marks)
marks.reverse()
print(marks)
marks.sort(reverse=True)
print(marks)
marks.insert(2, 80)
print(marks)    
marks.remove(78)
print(marks)
marks.pop(0)
print(marks)